config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get  "home/about"  => "homes#about"

  resources :books do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end

  resources :users
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
    if @book.save
      redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully created.'
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <% if @book.errors.any? %>
    <h2 class="warning"><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul class="warning">
      <% @book.errors.full_messages.each do |massage| %>
      <li><%= massage %></li>
      <% end %>
    </ul>
  <% end %>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %>

<p><%= link_to "Show", book_path %></p>
<p><%= link_to "Back", books_path %></p>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/user', user: @user %>
      <%= render 'layouts/book', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <%= render 'layouts/list'%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/user', user: @user %>
      <%= render 'layouts/book', book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>

      <table>
        <tr>
          <td scope="row">
            <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.png", size:'50' %>
            <% end %>
          </td>
          <td scope="row"><%= link_to @book.title, book_path(@book) %></td>
          <td scope="row"><%= @book.body %></td>
        </tr>
        <tr>
          <td scope="row"><%= link_to @user.name, user_path(@book.user) %></td>
          <td scope="row"></td>
          <td scope="row"></td>
        </tr>
        <tr>
          <td id="favorites_buttons_<%= @book.id %>">
            <%= render 'favorites/favorite', book: @book %>
          </td>
        </tr>

        <tr>
          <% if @book.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_book_path(@book) %></td>
          <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "Are you sure?" %></td>
          <% end %>
        </tr>
      </table>

      <div>
        <p>コメント件数：<%= @book.book_comments.count %></p>
        <% @book.book_comments.each do |book_comment| %>
          <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.png", size:'50' %>
          <%= book_comment.user.name %>
          <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
        <% if book_comment.user == current_user %>
          <div>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
          </div>
        <% end %>
        <% end %>
        </div>
        <div>
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>