config/routes.rb
Rails.application.routes.draw do
 devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get  "home/about"  => "homes#about"

  resources :books do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :book_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private

  def book_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
    if @book.save
      redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully created.'
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @users = User.all
  end

  def create
  @book = Book.new(book_params)
    if @book.save
      redirect_to ("/books/#{@book.id}"), notice: 'Book was successfully created.'
    else
      @books = Book.all
      render 'index'
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to ("/users/#{@user.id}"), notice: 'User was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_book.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %>prohibited this product from being saved:
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>New book</h1>

<%= form_with model:book, url:'/books', method: :post, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/layouts/_list.html.erb
<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th scope="col">Title</th>
      <th scope="col">Option</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td scope="row">
          <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.png", size:'50' %>
          <% end %>
        </td>
        <td scope="row"><%= link_to book.title, book_path(book) %></td>
        <td scope="row"><%= book.body %></td>
        <td id="favorites_buttons_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td scope="row">
          <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_user.html.erb
<h1>User info</h1>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png", size:'50x50' %>
<table>
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
</table>

<%= link_to edit_user_path(user) do %>
  <i class="fas fa-user-cog"></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9e8ff13473.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container">
    <body>
      <header class="navbar navbar-fixed-top">
        <nav class="nav navbar-left"><%= link_to "Bookers", root_path %></nav>
        <nav>
          <ul class="nav navbar-nav navbar-right flex-row">
          <% if user_signed_in? %>
          <li class="mx-2">
            <i class="fas fa-home"></i>
            <%= link_to "Home", user_path(current_user.id) %>
          </li>
          <li class="mx-2">
            <i class="fas fa-users"></i>
            <%= link_to "Users", users_path %>
          </li>
          <li class="mx-2">
            <i class="fas fa-book-open"></i>
            <%= link_to "Books", books_path %>
          </li>
          <li class="mx-2">
            <i class="fas fa-sign-out-alt"></i>
            <%= link_to "logout", destroy_user_session_path, method: :delete %>
          </li>

        <% else %>
          <li class="mx-2">
            <i class="fas fa-home"></i>
            <%= link_to "Home", root_path %>
          </li>
          <li class="mx-2">
            <i class="fas fa-link"></i>
            <%= link_to "About", home_about_path %>
          </li>
          <li class="mx-2">
            <i class="fas fa-user-plus"></i>
            <%= link_to "sign up", new_user_registration_path %>
          </li>
          <li class="mx-2">
            <i class="fas fa-sign-in-alt"></i>
            <%= link_to "login", new_user_session_path %>
          </li>
        <% end %>
          </ul>
        </nav>

      </header>

    <% if notice %>
    　<p><%= notice %></p>
    <% end %>
    <% if alert %>
      <p><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>

  <footer class="text-center">
    <p>CopyRight Infratop.inc</p>
  </footer>

  </div>
</html>